#!/bin/bash

if [[ ! -d "work" ]]
then
	echo "Work directory NOT found."
	echo "Creating work directory"
	vlib work
	sh com_lib
fi

if [[ -e "mult.sv" ]]
then
	echo "mult.sv found. Compiling"
	vlog -novopt mult.sv
fi

if [[ -e "mult_ctl.sv" ]]
then
	echo "mult_ctl.sv found. Compiling"
	vlog -novopt mult_ctl.sv
fi
 
if [[ -e "mult_syn" ]]
then
	echo "mult_syn found"
	design_vision-xg -f mult_syn 
fi

#"do_mult.do"
if [[ -e "mult.gate.v" ]]
then
	echo "Starting simulation in vsim"
	vsim -novopt mult -do mult.do
fi

if [[ ! -s "work/_info" ]]
then
	echo "cell is not compiled yet, please wait"
	#set location of synthesis library
	synop_lib="/nfs/guille/a1/cadlibs/synop_lib/SAED_EDK90nm/Digital_Standard_Cell_Library/verilog"
	
	echo "***** Compile synthesis library into work *****"
	vlog $synop_lib/*  -work work

fi
